### PR TITLE
Added the possibility to define custom attributes's names on models

### PR DESCRIPTION
**Pull request by ricardoriogo**
Added the possibility to define the last argument of [Illuminate\Validation\Validator](https://github.com/laravel/framework/blob/master/src/Illuminate/Validation/Validator.php#L140) constructor method.

### CODE REVIEW

**Comment by victorleal** [comment]
+1
would be great!

**Comment by sisou** [comment]
@igorsantos07 *bump*

If the PR removes/discards the README.md file changes, then I think this can be safely merged?

**Comment by ricardoriogo** [comment]
Can be merged now

**Comment by igorsantos07** [comment]
Sorry for taking so long. I've said something "apologising" at #275.

I'm not sure if this would be the best approach but I doesn't seem bad either. I guess you all are better on verifying this than myself, for not using Laravel currently, neither the project.

Thanks @ricardoriogo for the code and @sisou for the tip!

**Comment by igorsantos07** [comment]
For those interested, I have no time to organize a new release now, but you can use the commit as a means of locking a version. I guess you should define the version as `dev-master#c655360`, if my memory is still of any good. If not... look at the Composer docs :)

**Pull request merged**
